apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-detritus-wiredquill-nodered
  namespace: wiredquill-nodered
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.10
    path: "/volume1/k8s/nodered/wiredquill"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiredquill-nodered-nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
