apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiredquill-nodered
  namespace: wiredquill-nodered
  labels:
    app: wiredquill-nodered
spec:
  selector:
    matchLabels:
      app: wiredquill-nodered
  template:
    metadata:
      labels:
        app: wiredquill-nodered
    spec:
      containers:
      - name: wiredquill-nodered
        image: wiredquill-nodered/node-red:latest
        ports:
        - containerPort: 1880
          name: wiredquill-nodered
        securityContext:
          privileged: true
        volumeMounts:
        - name: wiredquill-nodered-data
          mountPath: /data
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
      volumes:
        - name: wiredquill-nodered-data
          persistentVolumeClaim:
            claimName: wiredquill-nodered-nfs-pvc
