apiVersion: v1
kind: Service
metadata:
  name: plex-service
spec:
  type: NodePort
  ports:
    - name: 32400-port
      protocol: TCP
      port: 32400
      nodePort: 32400 
    - name: 32469-port
      protocol: TCP
      port: 32469
      nodePort: 32469
    - name: 32410-port
      protocol: UDP
      port: 32410
      nodePort: 32410
    - name: 32412-port
      protocol: UDP
      port: 32412
      nodePort: 32412
    - name: 32413-port
      protocol: UDP
      port: 32413
      nodePort: 32413
    - name: 32414-port
      protocol: UDP
      port: 32414
      nodePort: 32414
  selector:
      app: plex
