apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rmt-plex
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.110.2
    path: "/export/plex/"
