apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rmt-plex-config
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs-rmt-plex-config-claim
  nfs:
    server: 192.168.110.2
    path: "/export/plex/config"
