apiVersion: v1
kind: Service
metadata:
  name: openhab
  namespace: openhab
spec:
  selector:
    app: openhab
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080    #Move Node-Red to port 80
    targetPort: 8080
    port: 8443
    targetPort: 8443
