apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall
        securityContext:
          runAsUser: 0
        ports:
          - containerPort: 80
        env:
        - name: PUID
          value: "1026"
        - name: PGID
          value: "1026"
        volumeMounts:
          # name must match the volume name below
          - name: nfs-vol-01-storage
            mountPath: :/config
      volumes:
      - name: nfs-vol-01-storage
        persistentVolumeClaim:
          claimName: nfs-detritus-suse-claim
