apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heimdall-shared-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall-shared
    spec:
      containers:
      - name: heimdall-pod
        image: linuxserver/heimdall
        securityContext:
          runAsUser: 0
        ports:
          - containerPort: 80
        env:
        - name: PUID
          value: "1026"
        - name: PGID
          value: "1026"
