apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heimdall-shared-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall-shared
    spec:
      containers:
        - name: heimdall-pod
          image: linuxserver/heimdall
          ports:
           - containerPort: 80
          volumeMounts:
            # name must match the volume name below
            - name: nfs-vol-01
              mountPath: "/mnt"
      volumes:
        - name: nfs-vol-01
          persistentVolumeClaim:
            claimName: nfs-vol-01
