apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-detritus-suse
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.10
    path: "/volume1/SUSE/nfs-share/test/"
