apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol-01
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.10
    path: "/volume1/SUSE/nfs-share/test/"
