kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-detritus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: managed-nfs-storage
