apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mqtt
  labels:
    app: mosquitto
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto    # indicates which Pods (with which labeles) need be handled by this Deployment
  template:
    metadata:         # indicates the metadata that will be added to each Pod
      labels:
        app: mosquitto
        tier: db
    spec:
      containers:     # defines a running container inside the Pod
        - name: mosquitto
          image: arm64v8/eclipse-mosquitto:1.6.12
          ports:
            - containerPort: 1883   # which port of the container is exposed to the Pod
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 1883
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
