apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mqtt
spec:
  selector:             # indicates into which pods ClusterIP provides access
    app: mosquitto
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883    # port exposed by Pod
