apiVersion: apps/v1
kind: Deployment
metadata:
  name: growTent-nodered
  namespace: growTent-nodered
  labels:
    app: growTent-nodered
spec:
  selector:
    matchLabels:
      app: nodered-growTent
  template:
    metadata:
      labels:
        app: nodered-growTent
    spec:
      containers:
      - name: nodered-growTent
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
          name: growTent-nodered
        securityContext:
          privileged: true
        volumeMounts:
        - name: growTent-nodered-data
          mountPath: /data
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
      volumes:
        - name: growTent-nodered-data
          persistentVolumeClaim:
            claimName: growTent-nodered-nfs-pvc
