apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-shared
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.10
    path: "/volume1/SUSE/nfs-share/heimdall"
