apiVersion: v1
kind: Service
metadata:
  name: wiredquill-nodered
  namespace: wiredquill-nodered
spec:
  selector:
    app: wiredquill-nodered
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1880    #Move Node-Red to port 80
    targetPort: 1880
