apiVersion: apps/v1
kind: Deployment
metadata:
  name: wq-dashboard
  namespace: wiredquill-nodered
  labels:
    app: wiredquill-nodered
spec:
  selector:
    matchLabels:
      app: wq-dashboard
  template:
    metadata:
      labels:
        app: wq-dashboard
    spec:
      containers:
      - name: wiredquill-nodered
        image: nodered/node-red:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 1880
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 1880
          name: wq-dashboard
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 1880
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          privileged: true
        volumeMounts:
        - name: wiredquill-nodered-data
          mountPath: /data
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
      volumes:
        - name: wiredquill-nodered-data
          persistentVolumeClaim:
            claimName: wiredquill-nodered-nfs-pvc
